<?php

/**
 * @file
 * Integrates the DPS PxPay gateway with Drupal Commerce!
 */


/*******************************************************************************
 * Hook Functions (Drupal)
 ******************************************************************************/

// Make sure DPS always has access to send IPNs.
function commerce_dps_pxpay_log_access() {
  return TRUE;
}

/**
 * Implementation of hook_perm().
 */
function commerce_dps_pxpay_permission() {
  return array(
    'administer commerce dps pxpay' => array(
      'title' => t('Administer Commerce DPS PXPay'),
      'description' => t('Perform administration tasks for Commerce DPS PXPay'),
    ));
}


/*******************************************************************************
 * Hook Functions (Drupal Commerce)
 ******************************************************************************/

function commerce_dps_pxpay_commerce_payment_method_info() {
  return array(
    'commerce_dps_pxpay' => array(
      'title' => t('Commerce Payment Express (PxPay)'),
      'short_title' => t('DPS'),
      'display_title' => t('Credit card'),
      'description' => t('Provides integration with the DPS PxPay payment gateway.'),
      'terminal' => FALSE,
      'offsite' => TRUE,
      'offsite_autoredirect' => TRUE,
    ),
  );
}


/*******************************************************************************
 * Callback Functions, Forms, and Tables
 ******************************************************************************/

/**
 * Payment method callback: settings form.
 */

function commerce_dps_pxpay_settings_form($settings = NULL) {
$form = array();

  $settings = (array) $settings + array(
    'commerce_dps_pxpay_userid' => variable_get('commerce_dps_pxpay_userid', 'Sample User'),
    'commerce_dps_pxpay_key' => variable_get('commerce_dps_pxpay_key', 'Sample Key'),
    'commerce_dps_pxpay_server' => variable_get('commerce_dps_pxpay_server', 'https://sec.paymentexpress.com/pxpay/pxaccess.aspx'),
    'commerce_dps_pxpay_currency' => variable_get('commerce_dps_pxpay_currency', 'NZD'),
    'commerce_dps_pxpay_cancel_return_url' => variable_get('commerce_dps_pxpay_cancel_return_url', 'cart'),
    'commerce_dps_pxpay_refprefix' => variable_get('commerce_dps_pxpay_refprefix', 'Website Order'),
  );  

  $form['commerce_dps_pxpay_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('PxPay User Id'),
    '#description' => t('PxPay User Id that was issued by Payment Express.'),
    '#default_value' => $settings['commerce_dps_pxpay_userid'],
    '#required' => TRUE,
  );
  $form['commerce_dps_pxpay_key'] = array(
    '#type' => 'textfield',
    '#title' => t('PxPay key'),
    '#description' => t('PxPay Key that was issued by Payment Express.'),
    '#default_value' => $settings['commerce_dps_pxpay_key'],
    '#required' => TRUE,
  );
  $form['commerce_dps_pxpay_server'] = array(
    '#type' => 'select',
    '#title' => t('PxPay server'),
    '#description' => t('Sign up for and use a Sandbox account for testing.'),
    '#options' => array(
      'https://sec.paymentexpress.com/pxpay/pxaccess.aspx' => ('Live'),
    ),
    '#default_value' => $settings['commerce_dps_pxpay_server'],
    '#required' => TRUE,
  );
  $form['commerce_dps_pxpay_currency'] = array(
    '#type' => 'select',
    '#title' => t('Currency code'),
    '#description' => t('Transactions can only be processed in one of the listed currencies.'),
    '#options' => _commerce_dps_pxpay_currency_array(),
    '#default_value' => $settings['commerce_dps_pxpay_currency'],
  );
  $form['commerce_dps_pxpay_cancel_return_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Cancel return URL'),
    '#description' => t('Specify the path customers who cancel their DPS PxPay payment will be directed to when they return to your site.'),
    '#default_value' => $settings['commerce_dps_pxpay_cancel_return_url'],
    '#size' => 32,
    '#field_prefix' => url(NULL, array('absolute' => TRUE)) . (variable_get('clean_url', 0) ? '' : '?q='),
  );
  $form['commerce_dps_pxpay_refprefix'] = array(
    '#type' => 'textfield',
    '#title' => t('Merchant Reference Prefix'),
    '#description' => t('Added before order number sent to DPS, ie Website Order #1234'),
    '#default_value' => $settings['commerce_dps_pxpay_refprefix'],
    '#required' => TRUE,
  );
  
  return $form;
}


/**
 * Payment method callback: checkout form.
 */
function commerce_dps_pxpay_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $form['commerce_dps_pxpay_logo'] = array(
    '#markup' => l(
      theme_image(array(
        'path' => drupal_get_path('module', 'commerce_paymentexpress') . 'sites/all/modules/commerce_paymentexpress/images/dps_paymentexpress_small.png',
        'alt' => t('DPS - Payment Gateway by Payment Express.'),
        'title' => t('DPS - Payment Gateway by Payment Express.'),
        'attributes' => array('style' => 'float: left; margin: 1em 1em 1em 1.5em;'),
      )),
      'http://www.paymentexpress.com',
      array('html' => TRUE, 'attributes' => array('target' => '_blank'))
    ),
  );

  return $form;
}

/**
 * Payment method callback: checkout form validation.
 */
function commerce_dps_pxpay_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  // Make sure that it's possible to use the DPS payment gateway.
  $commerce_dps_pxpay_userid = variable_get('commerce_dps_pxpay_userid');
  $commerce_dps_pxpay_key = variable_get('commerce_dps_pxpay_key');
  if (empty($commerce_dps_pxpay_userid) || empty($commerce_dps_pxpay_key)) {
    drupal_set_message(t('The DPS payment gateway cannot be used at this time'), 'error');
    // Return FALSE to stop the submission flow.
    return FALSE;
  }
}

/**
 * Implements hook_redirect_form().
 */
function commerce_dps_pxpay_redirect_form($form, &$form_state, $order, $payment_method) {
  
  include('PxPay_Curl.inc');

  $pxpay = new PxPay_Curl(
    variable_get('commerce_dps_pxpay_server', 'https://sec.paymentexpress.com/pxpay/pxaccess.aspx'),
    variable_get('commerce_dps_pxpay_userid', ''),
    variable_get('commerce_dps_pxpay_key', '')
  );

  $request = new PxPayRequest();

  # the following variables are read from the form
  $merchant_reference = variable_get('commerce_dps_pxpay_refprefix', 'Website Order') ." #". $order->order_number;
  #Generate a unique identifier for the transaction
  $txn_id = uniqid($order->order_number);
  // $order->data['pxpay_txnid'] = $txn_id;

  $failure_url = url('commerce_dps_pxpay/'.$order->order_number.'/cancel', array('absolute' => TRUE));
  $success_url = url('commerce_dps_pxpay/'.$order->order_number.'/complete', array('absolute' => TRUE));

  // $data1 = $order->billing_name;
  $data1 = 'Test Data 1';

  // $billing_country = commerce_get_country_data(array('country_id' => $order->billing_country));
  // if (is_array($billing_country)) {
  //   $billing_country = $billing_country[0]['country_iso_code_2'];
  // }
  // else {
  //   $billing_country = FALSE;
  // }

  // $delivery_country = uc_get_country_data(array('country_id' => $order->delivery_country));
  // if (is_array($delivery_country)) {
  //   $delivery_country = $delivery_country[0]['country_iso_code_2'];
  // } else {
  //   $delivery_country = FALSE;
  // }

  // $data2 = array('Billing:');
  // if ($order->billing_street1) {
  //   $data2[] = $order->billing_street1;
  // }
  // if ($order->billing_street2) {
  //   $data2[] = $order->billing_street2;
  // }
  // if ($order->billing_city) {
  //   $data2[] = $order->billing_city;
  // }
  // if ($order->billing_country) {
  //   $data2[] = $order->billing_country;
  // }
  // $data2 = implode(' ', $data2);
  $data2 = 'Test Data 2';

  // $data3 = array('Delivery:');
  // if ($order->delivery_street1) {
  //   $data3[] = $order->delivery_street1;
  // }
  // if ($order->delivery_street2) {
  //   $data3[] = $order->delivery_street2;
  // }
  // if ($order->delivery_city) {
  //   $data3[] = $order->delivery_city;
  // }
  // if ($order->delivery_country) {
  //   $data3[] = $order->delivery_country;
  // }
  // $data3 = implode(' ', $data3);
  $data3 = 'Test Data 3';
  
  $amount = commerce_currency_amount_to_decimal($order->commerce_order_total['und'][0]['amount']);

  // Set PxPay properties
  $request->setMerchantReference($merchant_reference);
  $request->setAmountInput($amount);
  $request->setTxnData1($data1);
  $request->setTxnData2($data2);
  $request->setTxnData3($data3);
  $request->setTxnType("Purchase");
  $request->setCurrencyInput(variable_get('commerce_dps_pxpay_currency', 'NZD'));
  $request->setEmailAddress($order->mail);
  $request->setUrlFail($failure_url);  # can be a dedicated failure page
  $request->setUrlSuccess($success_url);  # can be a dedicated success page
  $request->setTxnId($txn_id);

  // Call makeRequest function to obtain input XML
  $request_string = $pxpay->makeRequest($request);

  // Obtain output XML
  $response = new MifMessage($request_string);

  // Parse output XML
  $url = $response->get_element_text("URI");
  $valid = $response->get_attribute("valid");

  commerce_order_save($order);

  // Redirect to payment page
  if ($valid) {
    // uc_order_comment_save($order->order_id, 0, t('Redirecting to DPS Px Pay.'), 'admin');
    drupal_goto($url);
  }
  else {
    unset($_SESSION['cart_order']);
    drupal_set_message(t("We're sorry.  An error occurred while processing your order that prevents us from completing it at this time. Please contact us and we will resolve the issue as soon as possible."), 'error');
    watchdog('commerce_dps_pxpay', 'Transaction request failed. Order ID: @orderid. XML: @xml', array('@orderid' => $order->order_id, '@xml' => $response->xml_), WATCHDOG_ERROR);

    drupal_goto(variable_get('commerce_dps_pxpay_cancel_return_url', 'cart'));
  }

  return;
}

/*******************************************************************************
 * Module and Helper Functions
 ******************************************************************************/

// Returns an array of possible currency codes.
function _commerce_dps_pxpay_currency_array() {
  //return drupal_map_assoc(array('AUD', 'CAD', 'CHF', 'EUR', 'GBP', 'HKD', 'JPY', 'MXN', 'NOK', 'NZD', 'PLN', 'SEK', 'SGD', 'USD'));
  return array(
    'CAD' => 'Canadian Dollar',
    'CHF' => 'Swiss Franc',
    'EUR' => 'Euro',
    'FRF' => 'French Franc',
    'GBP' => 'United Kingdom Pound',
    'HKD' => 'Hong Kong Dollar',
    'JPY' => 'Japanese Yen',
    'NZD' => 'New Zealand Dollar',
    'SGD' => 'Singapore Dollar',
    'USD' => 'United States Dollar',
    'ZAR' => 'Rand',
    'AUD' => 'Australian Dollar',
    'WST' => 'Samoan Tala',
    'VUV' => 'Vanuatu Vatu',
    'TOP' => 'Tongan Pa\'anga',
    'SBD' => 'Solomon Islands Dollar',
    'PNG' => 'Papua New Guinea Kina',
    'MYR' => 'Malaysian Ringgit',
    'KWD' => 'Kuwaiti Dinar',
    'FJD' => 'Fiji Dollar',
  );
}